const icons = {
  // logo: require('../icons/logo.png'),
  // pending_invoice: require('../icons/pending_invoice.png'),
  // request: require('../icons/request.png'),
  // rocket: require('../icons/rocket.png'),
  // unread_chat: require('../icons/unread_chat.png'),
  // enquiry: require('../icons/enquiry.png'),
  // appointments: require('../icons/appointments.png'),
  // manage_project: require('../icons/manage_project.png'),
  // support: require('../icons/support.png'),
  // profile: require('../icons/profile.png'),
  // about: require('../icons/about.png'),
  // logout: require('../icons/logout.png'),
  // menu: require('../icons/menu.png'),
  // camera: require('../icons/camera.png'),
  // resend: require('../icons/resend.png'),
  // back: require('../icons/back.png'),
  // email: require('../icons/email.png'),
  // chat_deselect: require('../icons/chat_deselect.png'),
  // profile_deselect: require('../icons/profile_deselect.png'),
  // home: require('../icons/home.png'),
  // invoice_deselect: require('../icons/invoice_deselect.png'),
  // check: require('../icons/check.png'),
  // checked: require('../icons/checked.png'),
  // unchecked: require('../icons/unchecked.png'),
  // delete: require('../icons/delete.png'),
  // down: require('../icons/down.png'),
  // add: require('../icons/add.png'),
  // filter: require('../icons/filter.png'),
  // male: require('../icons/male.png'),
  // female: require('../icons/female.png'),
  // add_image: require('../icons/add_image.png'),
  // download: require('../icons/download.png'),
  // clip: require('../icons/clip.png'),
  // send: require('../icons/send.png'),
  // manageProject: require('../icons/manageProject.png'),
  // privacy: require('../icons/privacy.png'),
  // terms: require('../icons/terms.png'),
  // cross: require('../icons/cross.png'),
  // sign_doc: require('../icons/sign_doc.png'),
  // pdf: require('../icons/pdf.png'),
  // conversation: require('../icons/conversation.png'),
  // ppt: require('../icons/ppt.png'),
  // file: require('../icons/file.png'),
  // lock: require('../icons/lock.png'),
  // cablogo: require('../icons/cablogo.png'),
  // bassproshops: require('../icons/bassproshops.png'),
  // car: require('../icons/car.png'),
  // user: require('../icons/user.png'),
  // calendar: require('../icons/calendar.png'),
  // giftbox: require('../icons/giftbox.png'),
  // coverImage: require('../icons/coverImage.png'),
  // comments: require('../icons/comments.png'),
  // verticalMenuDots: require('../icons/verticalMenuDots.png'),
  // like_filled: require('../icons/like_filled.png'),
  // group_white: require('../icons/group_white.png'),
  // post: require('../icons/post.png'),
  // notification_inverted: require('../icons/notification_inverted.png'),
  // groups_inverted: require('../icons/groups_inverted.png'),
  // research_inverted: require('../icons/research_inverted.png'),
  // tick: require('../icons/tick.png'),
  // blank_circle: require('../icons/blank_circle.png'),
  // loading: require('../icons/loading.json'),
  // favourite: require('../icons/favourite.png'),
  // trash: require('../icons/trash.png'),
  // reportPost: require('../icons/report.png'),
  // edit: require('../icons/edit.png'),s
};

// export const researchimg = [
//   require('../icons/land.png'),
//   require('../icons/tablet.png'),
// ];
// export const leaderboardimg = [
//   require('../icons/kenny.png'),
//   require('../icons/cameron.png'),
//   require('../icons/jeff.png'),
//   require('../icons/david.png'),
// ];

// export const leaderboard_topuserimg = [
//   require('../icons/kenny.png'),
//   require('../icons/amy.png'),
//   require('../icons/cameron.png'),
//   require('../icons/jeff.png'),
//   require('../icons/david.png'),
// ];

export default icons;
